### ISSUE TITLE
Minor fix in example

### ISSUE THREAD

**Issue by aliaadil** [pregiotek/ion-floating-menu#14]
Hi,

First, that you for all the effort you put in creating the plugin for ionic it has helped me greatly. 

I just wanted to point a minor issue in the Readme file where you give the example of using the floating button. In the HTML section it should  be 'icon-color="#fff"' instead of 'iconColor="#fff"'

Thought it might help other people!

Regards,
Ali

**Comment by ennedigi** [comment]
Thank you for your feedback, I corrected the typo :+1:
