### ISSUE TITLE
typo in readme?

### ISSUE THREAD

**Issue by Jbarget** [pregiotek/ion-floating-menu#15]
heya

just spotted a typo in your readme:
- Menu similar to the Material UI Floating Action Button

should it be?:
- Menu similar to the Material UI Menu

**Comment by thgfrzm** [comment]
another on the snippet:

```
<ion-floating-button click="myEvent()" has-footer="false" button-color="#2AC9AA" icon="ion-plus" iconColor="#fff">
</ion-floating-button>

<ion-content>
    ...
```

on the attribute: -iconColor- -> _icon-color_

**Comment by ennedigi** [comment]
Thanks, corrected
