### ISSUE TITLE
Add label to floating-item

### ISSUE THREAD

**Issue by Shinzah** [pregiotek/ion-floating-menu#2]
It should be nice too, to be able to add a label in the left of an ion-floating-item.

Like that :
http://i.stack.imgur.com/BHzxI.png

**Comment by pregiotek** [comment]
@Shinzah Thanks for the comment! We will include it in the next release!
If you are using the lib and you are happy about it, do not forget to rate it on the Ionic Market! Thanks

**Comment by Shinzah** [comment]
I will do it ! Thank for your job !

**Comment by pregiotek** [comment]
@Shinzah  I included the attribute `text` and `text-class` to define labels.
Let me know if everything is alright. 

ps
Thanks for the review!

**Comment by Shinzah** [comment]
Hi, everything work fine ! Thank you !
(Don't forget to bump your version for bower usage)

**Comment by pregiotek** [comment]
Great, Thanks for reminding me. I'll do it now!
