### ISSUE TITLE
Hide or show with scroll position on page

### ISSUE THREAD

**Issue by feruzm** [pregiotek/ion-floating-menu#22]
This is great directive!
Would it be possible to show or hide button menu with certain part of screen?

Let's say, it will be visible and when scroll position reaches certain threshold it will be hidden. Or opposite, it will stay hidden and when we reach scroll handle/threshold it will be shown.
ref:
[$ionicScrollDelegate](http://ionicframework.com/docs/api/service/$ionicScrollDelegate/)

**Comment by ennedigi** [comment]
With version 1.2 you can specify ng-if or ng-show on the ion-floating-button and ion-floating-menu elements. In this way you can define your hiding logic based on the $ionicScrollDelegate.
