### ISSUE TITLE
Injection Error

### ISSUE THREAD

**Issue by Rebaiahmed** [pregiotek/ion-floating-menu#27]
Hello , i When i put the    "ion-floating-button click="myEvent()" has-footer="false" button-color="#2AC9AA" icon="ion-plus" icon-color="#fff""
  </ion-floating-button> in my code then i get this error 
![capture du 2016-10-01 12 42 44](https://cloud.githubusercontent.com/assets/13053759/19013839/965ae062-87d4-11e6-82f1-71ab31be57fb.png)

**Comment by ennedigi** [comment]
Which version are you using? Did you try pre-released 1.4? @Rebaiahmed

**Comment by ennedigi** [comment]
I will close the issue since I didn't have any feedback. If you still have problems, please reopen @Rebaiahmed
