### ISSUE TITLE
ion-floating-menu -  I would like feature to allow control over size of the buttons/menu

### ISSUE THREAD

**Issue by haresh333** [pregiotek/ion-floating-menu#31]
I would like the floating button/menu to be bit smaller. can u export some attribute that can allow to create smaller buttons

**Comment by ennedigi** [comment]
You can achive this using some custom css on you application.

For the button size, e.g. 40px :

`#floating-menu { width: 40px !important; height: 40px !important; line-height: 40px !important; } 
`
For the icon size, e.g. 10px:

 `#floating-menu .icon.menu-icon { font-size: 10px !important; } #floating-menu li i{ font-size: 10px !important; }`
