### ISSUE TITLE
Dependency Problem

### ISSUE THREAD

**Issue by ng22792** [pregiotek/ion-floating-menu#36]
I have added the plugin using command line, but after that when I add a dependency to my angular module, something like this:

angular.module('ionicApp', ['ionic','ion-floating-menu','starter.controllers','starter.companycontrollers', 'starter.directives', 'starter.services'])

then after starting app in browser using  " ionic serve --lab " command, the white output is shown, meaning the app crashed because of wrong code. things work fine after I take out this dependency. (,'starter.controllers','starter.companycontrollers', 'starter.directives', 'starter.services' are my controllers and services, please ignore). I am pretty sure the plugin is installed as I have tried installing multiple times. Could it be an Angular JS version problem?
 I have also added CSS, JS link in my index.html. 

my www folder: 
[www.zip](https://github.com/pregiotek/ion-floating-menu/files/582630/www.zip)

my output screenshot:
![screenshot 6](https://cloud.githubusercontent.com/assets/14888717/20166898/d641bc4a-a73d-11e6-9bc0-b507ee6a57b0.png)

**Comment by ennedigi** [comment]
Hi @ng22792,

I see that in your index.html file you load ion-floating-menu javascript file before the ionic bundle, i.e. before the angular library. This is the reason why you are getting the error angular not found.

Please assure that you always load angular library first, e.g. 

<script src="cordova.js"></script>
<script src="lib/angular/angular.js"></script>
<script src="js/ion-floating-menu.js" type="text/javascript"></script>

Cheers
