### ISSUE TITLE
Can't hide or show

### ISSUE THREAD

**Issue by josecostamartins** [pregiotek/ion-floating-menu#37]
Apparently de ion-floating-button cannot change its state when it comes to hiding/showing it on screen.

If it's shown, it will always be displayed, otherwise, will never be displayed.

Not even ng-if works.

**Comment by ennedigi** [comment]
Hi @josecostamartins,

can you send me an example of the issue?

Thanks

**Comment by josecostamartins** [comment]
My problem occurred when using a ng-map directive in conjunction with the ion-float-button, but I cannot reproduce it and, oddly enough, is now working as expected in my application as well.

I'm closing this down.
