### ISSUE TITLE
Custom image for the floating button

### ISSUE THREAD

**Issue by ai2010** [pregiotek/ion-floating-menu#42]
Can I ask you how to add a custom images to the ones predefined (ion-camera, ion-plus etc.)?

**Comment by stephenlane** [comment]
here you go

`<ion-floating-item style="background-color:#FF7900;" icon-image-class="homeIcons" icon-image-path="img/ico/image_here.png" text="some text"></ion-floating-item>`

**Comment by ai2010** [comment]
what?

**Comment by stephenlane** [comment]
with the code below you can include any image you want. I initially hacked this to do it and then it was implemented properly

`<ion-floating-item style="background-color:#FF7900;" icon-image-class="homeIcons" icon-image-path="img/ico/image_here.png" text="some text"></ion-floating-item>`

**Comment by ai2010** [comment]
for some reason if I copy and paste your code it does not work and continue to see the predefined plus image and the background around is white:
<img width="320" alt="capture d ecran 2017-01-02 a 20 41 35" src="https://cloud.githubusercontent.com/assets/8618000/21595972/fd501850-d12b-11e6-8550-79042c38fe2d.png">
. I tried:
```
<ion-floating-menu>
	    <ion-floating-item click="PopupOffer()" has-footer="false" style="background-color:#FF;" icon-image-class="homeIcons" icon-image-path="img/male.png"></ion-floating-item>
	</ion-floating-menu>
```

**Comment by ai2010** [comment]
ok the white background was due to the wrong color #FF. Putting the original color the white background disappears. Still the rest of the problem

**Comment by stephenlane** [comment]
homeicons was a css class i created. try it without it

**Comment by ai2010** [comment]
Unfortunately still the same problem. I did:
```
<ion-floating-menu>
	    <ion-floating-item click="PopupOffer()" has-footer="false" style="background-color:#FF79;" icon-image-path="img/ico/logo.png">
	    </ion-floating-item>
	</ion-floating-menu>
```

**Comment by ai2010** [comment]
As a further test I tried to change the color of the normal button:
`<ion-floating-menu>
	    <ion-floating-item click="PopupOffer()" has-footer="false"  icon-color="#F0F8FF">
	    </ion-floating-item>
	</ion-floating-menu>
`
but the button is still as before. It seems that it cannot be edited no matter what you change. Inside the ion-floating-menu.js in the function function ionFloatingMenuCtrl($scope, $rootScope, $ionicBackdropIon) { the console log prints correctly the value ($scope.iconColor) but the screen is not affected. Do you know why?

**Comment by ai2010** [comment]
I found the problem: I set 'replace: true' instead of false and the customization starts to appear!
