### ISSUE TITLE
GetEvents

### ISSUE THREAD

**Issue by nunomsh** [pregiotek/ion-floating-menu#9]
Is it possible to get the events? For example **onMenuOpen()** do something ...
In my case, the menu items above the page content, it's kind of confuse, so I was trying to apply some div similar to ionic backdrop, that will create an trasparency above all content, and keep only the menu items, but only apply it when the menu is open
![image](https://cloud.githubusercontent.com/assets/2600175/13993943/7f4a0566-f11a-11e5-9cd8-cc5aa77903e1.png)

**Comment by nunomsh** [comment]
Ok, after a few tests, I manage to get this working. Not the best solution, but it works.
I simple pass on to rootscope the true/false on the setClose/setOpen functions. Then in the template, create a simple div, with ng-show

Result: it shows the backdrop when menu open, and hides it on close

**Comment by ocean99988** [comment]
Hi nunomsh, able to point us to the right direction? we are trying to achieve this too

**Comment by ennedigi** [comment]
Added two events:

floating-menu:open: Triggered when the menu opens
floating-menu:close: Triggered when the menu closes

in version 1.2
